### ISSUE TITLE
Extract API module from registration module.

### ISSUE THREAD

**Issue by nalkhovikleverx** [nalkhovikleverx/GoEdu#11]
We need to extract public API of the `registration` module into the separate package which other modules can depend on. To do it we need to define a facade interface with collection of operation that module supports with appropriate input and output parameters. It would serve as **public contract** of this module.

```go
type RegistrationService interface {
        RegisterNewUser(context.Context, RegisterNewUserCommand) (RegisterNewUserCommandResult, error)
        ...
}
```

We have to duplicate types that lay down in `application` layer into this separate module because the may change by the different reasons. All types in the `registration` module is considered as implementation specific.

_Originally posted by @nalkhovikleverx in https://github.com/nalkhovikleverx/GoEdu/discussions/10#discussioncomment-9394218_

**Comment by aliaksei-kosyrau-leverx** [comment]
How i see, i only need to implement functions with the same names and signatures  https://golangbyexample.com/facade-design-pattern-in-golang/

**Comment by nalkhovikleverx** [comment]
Basically yes. You need to write a separate package and store public types and interfaces that could be used by other modules as a programmatic contract to this module. The module itself will implement it, but we will do it later. For now, we can place it in this path: `internal/registration/api`. This package should not import anything from `internal/registration/internal` package (basically it should not import anything but standard library packages like `context, fmt`). The types themselves should use the basic data types like strings, integers, and so on because these types are easy to map.

For now, I don't really know what drawbacks this approach has in implementation, but advantages are clear to me.
